name: Deploy PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - name: Copy
        run: |
          mkdir out
          cp ./thesis.pdf ./out/thesis.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: out/thesis.pdf
          